# spring.application.name=alumni_connect

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/alumni_connect
spring.datasource.username=root
spring.datasource.password=Shreya03

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
